-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 10:42:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema efo
-- -----------------------------------------------------
-- 线上文件管理系统
DROP SCHEMA IF EXISTS `efo` ;

-- -----------------------------------------------------
-- Schema efo
--
-- 线上文件管理系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `efo` DEFAULT CHARACTER SET utf8 ;
USE `efo` ;

-- -----------------------------------------------------
-- Table `efo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efo`.`user` ;

CREATE TABLE IF NOT EXISTS `efo`.`user` (
  `id` INT NOT NULL COMMENT '用户编号',
  `username` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '用户名',
  `real_name` VARCHAR(45) NULL DEFAULT '' COMMENT '真实姓名',
  `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱地址',
  `password` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '登录密码',
  `permission` INT NOT NULL DEFAULT 1 COMMENT '0（禁止登录），1（正常，普通用户），2（正常，管理员），3（正常，超级管理员）',
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp COMMENT '注册时间',
  `last_login_time` DATETIME NOT NULL DEFAULT current_timestamp COMMENT '最后一次登录时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  UNIQUE INDEX `create_time_UNIQUE` (`create_time` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `efo`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efo`.`category` ;

CREATE TABLE IF NOT EXISTS `efo`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `cat_id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '文件分类';


-- -----------------------------------------------------
-- Table `efo`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efo`.`file` ;

CREATE TABLE IF NOT EXISTS `efo`.`file` (
  `id` BIGINT NOT NULL COMMENT '编号',
  `name` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '文件名',
  `suffix` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '文件后缀\n',
  `base64` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '文件名的base64编码',
  `local_url` VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '本地路径',
  `visit_url` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '客户端访问路径',
  `size` BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小，单位bit',
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp COMMENT '创建时间',
  `description` VARCHAR(1024) NULL DEFAULT '' COMMENT '文件描述',
  `check_times` INT NOT NULL DEFAULT 0 COMMENT '查看次数',
  `download_times` INT NOT NULL DEFAULT 0 COMMENT '下载次数',
  `tag` VARCHAR(45) NULL DEFAULT '' COMMENT '文件标签',
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `file_id_UNIQUE` (`id` ASC),
  INDEX `fk_file_user_idx` (`user_id` ASC),
  INDEX `fk_file_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_file_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `efo`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `efo`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '文件列表';


-- -----------------------------------------------------
-- Table `efo`.`download`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `efo`.`download` ;

CREATE TABLE IF NOT EXISTS `efo`.`download` (
  `id` BIGINT NOT NULL COMMENT '编号',
  `create_time` DATETIME NOT NULL DEFAULT current_timestamp COMMENT '下载时间',
  `user_id` INT NOT NULL,
  `file_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_download_user1_idx` (`user_id` ASC),
  INDEX `fk_download_file1_idx` (`file_id` ASC),
  CONSTRAINT `fk_download_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `efo`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_download_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `efo`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '下载历史表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
